### All Lights ###
- platform: template
  switches:
    house_lights:
      friendly_name: 'House Lights'
      value_template: "{{ is_state('group.all_lights', 'on') or is_state('switch.table_lamp', 'on') or is_state('switch.fairy_lights', 'on') }}"
      turn_on:
        - service: light.turn_on
          entity_id: group.all_lights
        - service: switch.turn_on
          entity_id: switch.table_lamp
        - service: switch.turn_on
          entity_id: switch.fairy_lights
      turn_off:
        - service: light.turn_off
          entity_id: group.all_lights
        - service: switch.turn_off
          entity_id: switch.table_lamp
        - service: switch.turn_off
          entity_id: switch.fairy_lights

### Master Switch ###
- platform: template
  switches:
    master_switch:
      friendly_name: 'Master Switch'
      value_template: "{{ is_state('switch.house_lights', 'on') or is_state('remote.living_room', 'on') or is_state('switch.template_samsung_tv', 'on') }}"
      turn_on:
        - service: switch.turn_on
          entity_id: switch.house_lights
        - service: remote.turn_on
          entity_id: remote.living_room
        - service: switch.turn_on
          entity_id: switch.template_samsung_tv
        # - service: switch.turn_on
          # entity_id: switch.template_home_server
      turn_off:
        - service: switch.turn_off
          entity_id: switch.house_lights
        - service: remote.turn_off
          entity_id: remote.living_room
        - service: switch.turn_off
          entity_id: switch.template_samsung_tv
        # - service: switch.turn_off
          # entity_id: switch.template_home_server
