### Server ###
- platform: wake_on_lan
  mac_address: !secret wol_mac
  name: Home Server
  host: !secret wol_ip
  turn_off:
    service: shell_command.server_shutdown
  
### All Lights ###  
- platform: template
  switches:
    house_lights:
      friendly_name: 'House Lights'
      value_template: "{{ is_state('group.all_lights', 'on') or is_state('switch.table_lamp', 'on') }}"
      turn_on:
        - service: light.turn_on
          entity_id: group.all_lights
        - service: switch.turn_on
          entity_id: switch.table_lamp
      turn_off:
        - service: light.turn_off
          entity_id: group.all_lights
        - service: switch.turn_off
          entity_id: switch.table_lamp

### RM Mini ###
- platform: broadlink
  host: !secret broadlink_host1
  mac: !secret broadlink_mac1        

### RM Pro ###  
- platform: broadlink
  host: !secret broadlink_host2
  mac: !secret broadlink_mac2
  switches:
    tv_samsung:
      friendly_name: "Samsung TV Power"
      command_on: 'JgDSAJGWETgSOBI4EhISExISEhISEhE4EjgSOBITERITEhISERMROBISEhMROBI4EhMSEhE4EhISOBI4EhMREhI3EzcTEhIABkiSlRI3EzcTOBISEhISEhISEhMRNxM3EzcTEhMREhISExATETgTEhISEjgSOBISEhIROBITETgTNxMSExESNxI4EhITAAZIkZYROBI4EjgSExESEhMTERETETgSOBI4EhMREhQREhIRExE4EhISExE4EjgSEhISEjgTERI4EzcSEhITETcSOBITEwANBQAAAAAAAA=='
      command_off: 'JgDSAJOUFTUVNRU1EhMREhQQFBAUEBU1FTUVNRISEhIUEBQQFBAUEBUQFBAUNRU1FRASEhI3FDYUNhQ2EhEVEBQ1FTUVEBQABkWUkxU1FTUVNRMSEhEVDxUQFBAUNRU1FTUTEhIRFBAVEBQQFBAUEBQQFDYUNhISEhIUNRU1FTUVNRMRFBAUNhQ2FBAVAAZElJQUNhU1FTUSEhISExEUEBQQFDYUNhQ2EhIUEBQQFBAUEBQQFQ8VEBQ1FTUTEhIRFDYUNhQ2FDUUEBUQFDUVNRUQFAANBQAAAAAAAA=='
    arlec1:
      friendly_name: "Power Switch 1"
      command_on: 'sgBgAhwKChwKHAocCRwKHAocChsKHBsLGwsbChsLChwbCxsLGwoKHAocChwbCgocCgABUQocChwaCwocGwoLGwsbHAoKHBsKChwcCgocChwKHAobCxsKHAocChsbCxwKGwsbCwkcHAobCxsLChsKHAocGwsKHAoAAVEJHAocGwsKHBsKChwKHBsKCxwbCgocGwsKGwsbChwKHAocChsKHAocGwsbCxsKGwsKHBsKHAobCwocChwKGxsLChwKAAFRChwKGxwKChwbCwobChwbCwocGwsKHBsKChwKHAocChwJHAocChwKHBsLGgsbCxsLChscCxoLGwsKHAocCRwbCwocCgABUQkcChwbCwocGwoKHAocGwsKHBsKChwbCwocChwKGwocChwKHAobCxsbCxsLGwsaCwocGwsbCxsKChwKHAocGwsJHAoAAVEKHAocGwoKHBsLChwKGxwKChwbCwocGwoKHQkcChwKHAocCR0JHAocGwocChsLGwsKHBsLGwobCwocChwKGxsLChwKAAFRChwJHBsLChwbCwkcChwbCwocGwoKHBsLChwKHAkcCxsKHAocChsKHRsKGwsbCxsLCR0bChsLGwsKGwsbChwbCwocCgABUAocChwbCwobGwsKHAocGwoKHRsKChwbCwocCR0JHAocChwKHAobChwbCxsLGwsbCgocGwsbCxsKChwKHAocGwoKHAoAAVEKHAocGwsJHBsLChsKHBwKChwbCwocGwoKHAocChsLHAkcChwKHAocGwobCxsLGwsKGxwKGwsbCwobCxsKHBsLChwKAAXcChwKHBsLCRw='
      command_off: 'sgBCAhsKGwsKHAocChwKGwocCgABUQocChwbCgocGwsKGwsbHAoKHBsLChscCgsbChwKHAobCxsKHAocChscChwKGwsKGwsbGwsbCxsLChsKHAocChwKHAoAAVEKGwocGwsKGxwKChwKHBsLChwbCgocGwsKGwsbChwKHAocChsKHAocHAobCxsLChsLGxsLGwsbCgocChwKHAocChsLAAFQChwKHBsKCxscCgocChscCgocHAoKHBsKChwKHAocChsLGwsbChwKHBsKGwscCgocChsbCxwKGwsKHAobChwKHAocCgABUAocChwbCwocGwoKHAocGwsKGxwKChwbCwobCxsLGwocChwKHAobChwbCxsLGwoLGwocGwsbCxsKChwKHAocChwKGwoAAVEKHAocGwsKGxwKChwKHBsLChsbCwocGwsKGwsbChwKHAocCRwKHAocGwsbCxsKChwKHBsLGwocCgocChwKGwsbChwKAAFRChwKGxwKCxsbCwocChwbCgocGwsKHBsKChwKHAocChwKHAobChwKHBsLGwocCgocChwbCxsLGwoKHAocChwKGwocCgABUQocChwbCgsbGwsKHAobHAoKHBsLChscCgocChwKHAkcCxsKHAocChwbChsLGwsKHAocGwobCxsLChwKGwocChwKHAoAAVEKGwsbGwsKHBsKCxsLGxsLChwbCwobGwsKHAocChwKGwocChwKHAobHAobCxsLChsKHBwKGwsbCwobChwKHAocChwKAAXcCxsKHAoc'
    arlec2:
      friendly_name: "Table Lamp"
      command_on: 'sgAsAhsKCxsbCwocChwbCgsbGwsKHBsLChsKHAocChwKHAobCxsKHBsLGwoKHBsLChwbChwKHAoKHAocGwsKGwocCgABUQobCxscCgocGwsKHAobHAoKHBsLChsbCwocChwKHAobChwKHAocChwaCxsLChwbCgsbGwsbCxsLChsKHBsLChwKHAoAAVALGwocGwsKHBsKChwKHBsLChwbCgocGwsKHAkcCxsKHAocChsLGwocGwsbCwocGwoLGxsLGwsbCgsbChwbCwocChwJAAFRChwKHBsLChsbCwocChwbCwkcHAoKHBsLChwKGwsbChwKHAocChsKHBsLGwoLHBsKChwbCxsLGwoKHAocGwsKHAkcCgABUQocChwbCwkcGwsKHAobHAoKHBsLChwbCgsbChwKHAocCRwKHAocChscChwKChwbCwocGwobCxsLChwKHBsKChwKHAoAAVEKHAkcGwsKHBsKCxsLGxsLChwbCwobGwsKHAocChsKHAocChsLHAkcGwsbCwocGwoKHBsLGwsbCgsbCxsbCwobCxwKAAFQChwKHBsLChscCgocChwbCwobHAoKHBsLCRwLGwocChwKHAobCxsKHBsLGwoKHBsLChwbChwKHAoKHAocGwoKHAocCgABUQobCxscCgocGwoLGwocHAoKHBsKChwbCwocChwKHAobCxsKHAocChwbChsLChwbCwkcHAobCxsLChsKHBwKChwKHAoABdwKGxsLChwKHBsLCRw='
      command_off: 'sgC8ABwKCxsKHAocChwKGwocChwKHBsKHAoKHAocChwbChwKGwsKHAocGwobCwocCgABUQobChwbCwocGwoLHAkcGwsKGxwKChwcCgocChwJHAocChwKHAobChwbCxsLChwKGwocGwsbCxsKCxsKHBsLGwsKHAoAAVAKHAsbGwsKGxwKCxwJHBsLChwbCgocGwsKHAocChsKHAocChwKHAobHAobCwocChsLGxsLGwsbCgocChwbCxsLChsKAAXcAAAAAAAAAAAAAAAA'
    arlec3:
      friendly_name: "Power Switch 3"
      command_on: 'sgBYAQocGwsKHAobGwsKHBsLChsbCwocChwKHAobChwKHAocChscCgocGwocCgocGwsbChwKCxsbCxsLChsLGwsAAVAKHAobHAoLGxsLChwKGxwKChwbCwocGwsKGwsbChwKHAobCxsKHAocGwoLGxwKHAoKHBsKHAocCgocGwsbCgocChwKAAFRChwKGxwKChwbCwobCxsbCwocGwoLGxwKCxsKHAobCxsLGwocChwKHBsKChwcChsLChscChwKHAoKHBsLGwoKHAocCgABUAsbCxsbCwocGwoLGwocGwsKGxwKChwbCwobCxsLGwocChwKGwsbChwbCwocGwocCgocGwsbChwKChwbCxsLChsKHAsAAVAKHAobHAoLGxsLChsLGxwKChwbCwocGwoLGwocChsLHAobChwKHAocGwsKGxwKGwsKHBsKHAobCwocGwsbCgsbChwKAAXc'
      command_off: 'sgCqAQsbCgABUQocChwbCgocHAoKHAocGwoKHBsLChwbCwobChwKHAocChsLGwocChwbCgocHAoKHAocGwsbChsLChwbChwKHAoKHAoAAVEJHAocGwsKHBsLChsKHBsLChwbCgocGwsKHAobChwKHAocChwJHAocGwsKHBsKChwKHBsLGwobCwocGwocChwKChwKAAFRChsLGxsLChwbCgsbChwbCwocGwsJHBsLChwKGwsbChwKHAocChsKHBsLChwbCgocChwbCxsKHAoKHBsLGwocCgocCgABUQobCxsbCwocGwsKGwsbHAoKHBsLChwbCgocChwKHAobCxsKHAocChwbCgsbGwsKHAocGwobCxsLChwbChsLGwsKGwsAAVAKHAocGwsKGxsLChwKHBsKChwbCwocGwoKHAocChwKHAocChsKHAocGwsKHBsKChwKHBsKHAobCwocGwsbChwKChwKAAFRChwKGxwKChwbCwocCRwcCgocGwoKHBsLChwKGwscCRwKHAocChwJHBwKChwbCgocCxsbCxsLGwoKHBsLGwsbCgsbCgAF3AAAAAAAAAAAAAAAAAAA'
