#### Action for Harmony input selection
- alias: Harmony
  hide_entity: True
  trigger:
    platform: state
    entity_id: input_select.harmony
    from: 'Select Input'
  action:
    - service: remote.turn_on
      entity_id: remote.living_room
      data_template:
        activity: >
          {% if is_state("input_select.harmony", "Watch TV") %}
            21450129
          {% elif is_state("input_select.harmony", "Watch TV with Surround") %}
            13915533
          {% elif is_state("input_select.harmony", "Watch TV via PVR") %}
            13474528
          {% elif is_state("input_select.harmony", "Play PS4") %}
            13332151
          {% else %}
          {% endif %}
    - service: input_select.select_option
      entity_id: input_select.harmony
      data_template:
        option: "Select Input"

#### Action for Harmony input selection to Power-Off
- alias: Harmony Off
  hide_entity: True
  trigger:
    platform: state
    entity_id: input_select.harmony
    to: 'Power Off'
  action:
    - service: remote.turn_off
      entity_id: remote.living_room
    - service: input_select.select_option
      entity_id: input_select.harmony
      data_template:
        option: "Select Input"

### Show Home Server Health when powered on        
- alias: Home Server On
  hide_entity: True
  trigger:
    platform: state
    entity_id: sensor.hp_ilo_server_power
    to: 'ON'
  action:
    service: group.set_visibility
    entity_id: group.server1
    data:
      visible: True

### Hide Home Server Health when powered off      
- alias: Home Server Off
  hide_entity: True
  trigger:
    - platform: state
      entity_id: sensor.hp_ilo_server_power
      to: 'OFF'
    - platform: homeassistant
      event: start
  condition:
    # condition needed for homeassistant startup trigger
    condition: state
    entity_id: sensor.hp_ilo_server_power
    state: 'OFF'
  action:
    service: group.set_visibility
    entity_id: group.server1
    data:
      visible: False

### Show Samsung TV control when powered on
- alias: Samsung Tv On
  hide_entity: True
  trigger:
    platform: state
    entity_id: media_player.samsung_tv
    to: 'on'
  action:
    service: group.set_visibility
    entity_id: group.samsung_tv
    data:
      visible: True
 
 ### Hide Samsung TV control when powered off
- alias: Samsung Tv Off
  hide_entity: True
  trigger:
    - platform: state
      entity_id: media_player.samsung_tv
      to: 'off'
    - platform: homeassistant
      event: start
  condition:
    # condition needed for homeassistant startup trigger
    condition: state
    entity_id: media_player.samsung_tv
    state: 'off'
  action:
    service: group.set_visibility
    entity_id: group.samsung_tv
    data:
      visible: False
      
### Turn off lights in morning when everyone leaves home
- alias: 'Away Mode - Lights Off'
  trigger:
    platform: state
    entity_id: group.all_devices
    to: 'not_home'
  condition:
    condition: time
    # At least one of the following is required.
    after: '07:15:00'
    before: '11:30:00'
  action:
    - service: light.turn_off
      entity_id: group.all_lights
    - service: notify.notify
      data_template:
        message: "Lights turned off"
          
### Turn on kitchen light in evening when someone enters home
- alias: 'Arrive Home - Kitchen Light On'
  trigger:
    platform: state
    entity_id: group.all_devices
    to: 'home'
  condition:
    condition: sun
    after: sunset
    # Optional offset value
    after_offset: "-00:30:00"
  action:
    - service: light.turn_on
      entity_id: light.1_kitchen
    - service: notify.notify
      data_template:
        message: "Kitchen Light turned on"
      
### Flash lights when Ashlei arrives home
- alias: 'Ashlei Home - Flash Lights'
  trigger:
    platform: state
    entity_id: device_tracker.iphone_6_plus
    to: 'home'
  action:
    - service: light.lifx_effect_pulse
      entity_id: group.all_lights
      data:
        brightness: 180
        color_name: pink
        period: 0.7
        cycles: 3
    - service: notify.notify
      data_template:
        message: "Ashlei has arrived home"

### Flash lights when Nick arrives home
- alias: 'Nick Home - Flash Lights'
  trigger:
    platform: state
    entity_id: device_tracker.lg_g4
    to: 'home'
  action:
    - service: light.lifx_effect_pulse
      entity_id: group.all_lights
      data:
        brightness: 180
        color_name: blue
        period: 0.7
        cycles: 3
    - service: notify.notify
      data_template:
        message: "Nick has arrived home"