############################################################
# Title:    Home Assistant Configuration                   #
# Author:   so3n                                           #
# Navigation:                                              #
#   Basic Setup                                            #
#   History Filter                                         #
#   Inputs                                                 #
#   Device Trackers                                        #
#   Remotes                                                #
#   Media Players                                          #
#   Google Assistant                                       #
#   Xiaomi Gateway                                         #
#   Cameras                                                #
#   Notifications                                          #
#   IFTTT                                                  #
#   Shell                                                  #
#   Weather                                                #
#   Climate                                                #
#   Covers                                                 #
#   Zones                                                  #
#   Binary Sensors                                         #
#   Vacuum                                                 #
#   Merged Files                                           #
#   No Longer Used                                         #
#                                                          #
############################################################


############ Basic Setup ############
homeassistant:
  name: !secret name
  latitude: !secret lat
  longitude: !secret long
  elevation: !secret elevation
  unit_system: metric
  time_zone: !secret timezone
  customize: !include customize.yaml
  whitelist_external_dirs:
    - /tmp
    - /share

http:
  # api_password: !secret http_pw
  # commented out below since using NGINX reverse proxy
  # ssl_certificate: /ssl/fullchain.pem
  # ssl_key: /ssl/privkey.pem
  # base_url: !secret url

frontend:
config:
updater:
hassio:
conversation:
history:
logbook:
logger:
  default: warning
  logs:
    custom_components.climate: debug
    custom_components.remote: debug
    # pyharmony: debug
    # homeassistant.components.light: debug
    # homeassistant.components.switch: debug
    # homeassistant.components.climate: debug
# introduction:
sun:
tts:
  platform: google


############ DB Recorder ############
recorder: !include recorder.yaml


############ Inputs ############
input_boolean:
  holiday_mode:
    name: Holiday Mode
    # initial: off
    icon: mdi:airplane
  cast_visible:
    name: Cast Visible
    initial: on
    icon: mdi:cast_visible
  fairy_lights:
    name: Fairy Lights Schedule
    # initial: on
    icon: mdi:pine-tree

input_select:
  timer_device:
    name: Device
    options:
      - Select...
      - Main AC
      - Bedroom AC
    initial: 'Select...'

input_number:
  timer_hours:
    name: Hours
    initial: 1
    min: 0
    max: 12
    step: 1

input_datetime:
  timer_off:
    name: Time to turn off
    has_date: true
    has_time: true


############ Device Trackers ############
device_tracker:
  - platform: gpslogger
    consider_home: 180
    new_device_defaults:
      track_new_devices: False
      hide_if_away: False
  - platform: unifi_direct
    host: !secret unifi_ip
    username: !secret unifi_user
    password: !secret unifi_pw
    consider_home: 180
    new_device_defaults:
      track_new_devices: False
      hide_if_away: False
  # - platform: unifi
  #   host: !secret hass_ip
  #   username: !secret unifi_user2
  #   password: !secret unifi_pw2
  #   site_id: !secret unifi_siteid
  #   verify_ssl: false
  #   detection_time: 180
  #   consider_home: 180
  #   new_device_defaults:
  #     track_new_devices: False
  #     hide_if_away: False


############ Remotes ############
remote:
  - platform: harmony
    name: Living Room
    host: !secret harmony_ip
    activity: 13474528


############ Media Players ############
media_player:
  - platform: samsungtv
    host: !secret samsungtv_ip
    name: Samsung TV
    mac: !secret samsungtv_mac
  - platform: braviatv
    host: !secret bravia_host
  # - platform: ps4
    # host: !secret ps4_host
    # ps4_ip: !secret ps4_ip
    # name: PlayStation 4
    # local_store: games
cast:


############ Google Assistant ############
google_assistant: !include google_assistant.yaml


############ Xiaomi Gateway ############
xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - host: !secret aqara_ip
      mac: !secret aqara_mac
      key: !secret aqara_key


############ Cameras ############
camera:
  ## xiaomi
  - platform: ffmpeg
    input: !secret cam1
    name: Study
  - platform: ffmpeg
    input: !secret cam2
    name: Family Room
  - platform: ffmpeg
    input: !secret cam3
    name: Kitchen
  ## swann/reolink
  # - platform: ffmpeg
  #   input: !secret reolink1
  #   name: Front 1
  # - platform: ffmpeg
  #   input: !secret reolink2
  #   name: Front 2
  # - platform: ffmpeg
  #   input: !secret reolink3
  #   name: Deck
  # - platform: ffmpeg
  #   input: !secret reolink4
  #   name: Side
  # - platform: ffmpeg
  #   input: !secret reolink5
  #   name: Backyard


############ Notifications ############
notify:
  - name: html5
    platform: html5
    gcm_api_key: !secret gcm-sender-key
    gcm_sender_id: !secret gcm-sender-id
  - name: gmail
    platform: smtp
    server: smtp.gmail.com
    port: 587
    timeout: 15
    sender: !secret smtp_email
    encryption: starttls
    username: !secret smtp_email
    password: !secret smtp_pw
    recipient:
      - !secret smtp_recipient1
    sender_name: My Home Assistant


############ IFTTT ############
ifttt:
  key: !secret ifttt_key


############ Shell ############
shell_command:
  server_shutdown: !secret server_shutdown


############ Weather ############
weather:
  - platform: bom
    station: !secret bom_station


############ Climate ############
climate:
  - platform: broadlink
    name: Bedroom
    host: !secret broadlink_host1
    mac: !secret broadlink_mac1
    ircodes_ini: 'www/climate_codes/panasonic.ini'
    min_temp: 16.0
    max_temp: 30.0
    target_temp: 20.0
    target_temp_step: 0.5
    temp_sensor: sensor.temp_bedroom
    default_operation: 'off'
    default_fan_mode: auto
    customize:
      operations:
        - 'off'
        - cool
        - dry
        - heat
      fan_modes:
        - low
        - mid
        - high
        - auto
  - platform: harmony
    name: Living Room
    host: !secret harmony_ip
    device_id: 58354062
    min_temp: 18
    max_temp: 30
    target_temp: 20
    target_temp_step: 1
    temp_sensor: sensor.temp_main
    default_operation: 'off'
    default_fan_mode: auto
    customize:
      operations:
        - 'off'
        - cool
        # - dry
        # - heat
      fan_modes:
        - low
        - med
        - high
        - auto


############ Covers ############
cover:
  - platform: mqtt
    name: Garage
    state_topic: "cmnd/garagestate/POWER2"
    command_topic: "cmnd/sonoffsv01/POWER"
    payload_open: "ON"
    payload_close: "ON"
    payload_stop: "ON"
    state_open: "OFF"
    state_closed: "ON"
    optimistic: false


############ Zones ############
zone:
  - name: Work
    latitude: !secret lat1
    longitude: !secret long1
    icon: mdi:briefcase
  - name: Work
    latitude: !secret lat2
    longitude: !secret long2
    icon: mdi:briefcase
  - name: Gym
    latitude: !secret lat3
    longitude: !secret long3
    icon: mdi:dumbbell
    radius: 50
  - name: Gym
    latitude: !secret lat4
    longitude: !secret long4
    icon: mdi:dumbbell
    radius: 50


############ Binary Sensors ############
binary_sensor:
  - platform: ping
    name: Online
    host: 8.8.8.8
    count: 5
    scan_interval: 300


############ Vacuum ############
vacuum:
  - platform: xiaomi_miio
    host: !secret vacuum_ip
    token: !secret vacuum_token


# konnected:
#   access_token: !secret konnected_token
#   api_host: !secret hass_url
#   devices:
#     - id: !secret konnected_mac
#       binary_sensors:
#         - zone: 1
#           type: motion
#       switches:
#         - zone: out
#       host: !secret konnected_host
#       port: !secret konnected_port
#       discovery: False        

# discovery:
#   ignore:
#     - apple_tv
#     - axis
#     - belkin_wemo
#     - bluesound
#     - bose_soundtouch
#     - denonavr
#     - directv
#     - frontier_silicon
#     - google_cast
#     - harmony
#     - ikea_tradfri
#     - logitech_mediaserver
#     - netgear_router
#     - openhome
#     - panasonic_viera
#     - philips_hue
#     - plex_mediaserver
#     - roku
#     - sabnzbd
#     - samsung_printer
#     - samsung_tv
#     - sonos
#     - songpal 
#     - tellstick
#     - wink
#     - yamaha
#     - yeelight
#     - xiaomi_gw


############ Merged Files ############
sensor: !include_dir_merge_list sensors/
switch: !include_dir_merge_list switches/
script: !include_dir_merge_named scripts/
automation: !include_dir_merge_list automations/
group: !include groups.yaml
