homeassistant:
  name: !secret name
  latitude: !secret lat
  longitude: !secret long
  elevation: !secret elevation
  unit_system: metric
  time_zone: !secret timezone
  customize: !include customize.yaml

# logger:
      
# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  api_password: !secret http_pw
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  base_url: !secret url

  
updater:
# discovery:
hassio:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

history:
  exclude:
    domains:
      - automation
      - weblink
      - updater
      - script
    entities:
      - sensor.last_boot
      - sensor.since_last_boot
      - sensor.date

logbook:
  exclude:
    entities:
      - sensor.last_boot
      - sensor.since_last_boot
      - sensor.date
      - automation.home_server_on
      - automation.home_server_off
      - automation.samsung_tv_on
      - automation.samsung_tv_off
      - automation.ps4_on
      - automation.ps4_off
      - automation.harmony_input_selection
      - automation.harmony_off
      - automation.harmony_activity_sync
      - automation.fujitsu_selection_cool_20
      - automation.fujitsu_selection_off
    domains:
      - sun
      - weblink

sun:

# Text to speech
tts:
  platform: google

light:
  - platform: lifx
    #server: !secret hass_ip
             
ifttt:
  key: !secret ifttt_key
  
emulated_hue:
  host_ip: !secret hass_ip
  listen_port: 80
  expose_by_default: false

device_tracker: !include_dir_merge_list device_trackers/
remote: !include_dir_merge_list remotes/      
media_player: !include_dir_merge_list media_players/    
input_select: !include_dir_merge_named input_select/
input_boolean: !include_dir_merge_named input_boolean/
shell_command: !include_dir_merge_named shell_command/
sensor: !include_dir_merge_list sensors/
switch: !include_dir_merge_list switches/
script: !include_dir_merge_named scripts/
automation: !include_dir_merge_list automations/
notify: !include_dir_merge_list notify/
zone: !include_dir_merge_list zones/
group: !include groups.yaml

# ios:

# ffmpeg:
  # ffmpeg_bin: /usr/bin/avconv
  
# camera:
  # - platform: ffmpeg
    # input: -rtsp_transport tcp -i rtsp://192.168.0.32/unicast
    # name: Cam_Study

