############################################################
# Title:    Home Assistant Configuration                   #
# Author:   so3n                                           #
# Navigation:                                              #
#   Basic Setup                                            #
#   History Filter                                         #
#   Inputs                                                 #
#   Device Trackers                                        #
#   Remotes                                                #
#   Media Players                                          #
#   Google Assistant                                       #
#   Xiaomi Gateway                                         #
#   Cameras                                                #
#   Notifications                                          #
#   IFTTT                                                  #
#   Shell                                                  #
#   Weather                                                #
#   Climate                                                #
#   Covers                                                 #
#   Zones                                                  #
#   Binary Sensors                                         #
#   Vacuum                                                 #
#   Alarm                                                  #
#   Merged Files                                           #
#   No Longer Used                                         #
#                                                          #
############################################################


############ Basic Setup ############
homeassistant:
  name: !secret name
  latitude: !secret lat
  longitude: !secret long
  elevation: !secret elevation
  unit_system: metric
  time_zone: !secret timezone
  customize: !include customize.yaml
  whitelist_external_dirs:
    - /tmp
    - /share

http:
  # api_password: !secret http_pw
  # commented out below since using NGINX reverse proxy
  # ssl_certificate: /ssl/fullchain.pem
  # ssl_key: /ssl/privkey.pem
  # base_url: !secret url

frontend:
config:
updater:
hassio:
conversation:
history:
logbook:
logger:
  default: warning
  logs:
    # custom_components.smartir.climate: debug
    custom_components.harmony_ac.climate: debug
    # custom_components.remote: debug
    # homeassistant.components.konnected: debug
    # pyharmony: debug
    # homeassistant.components.switch: debug
# introduction:
sun:
tts:
  platform: google_translate


############ DB Recorder ############
recorder: !include recorder.yaml


############ Inputs ############
input_boolean:
  holiday_mode:
    name: Holiday Mode
    # initial: off
    icon: mdi:airplane
  cast_visible:
    name: Cast Visible
    initial: on
    icon: mdi:cast_visible
  fairy_lights:
    name: Fairy Lights Schedule
    # initial: on
    icon: mdi:pine-tree
  motion_notifications:
    name: Motion Notifications
    icon: mdi:bell

input_select:
  timer_device:
    name: Device
    options:
      - Select...
      - Main AC
      - Bedroom AC
    initial: 'Select...'

input_number:
  timer_hours:
    name: Hours
    initial: 1
    min: 0
    max: 12
    step: 1

input_datetime:
  timer_off:
    name: Time to turn off
    has_date: true
    has_time: true


############ Device Trackers ############
device_tracker:
  - platform: unifi_direct
    host: !secret unifi_ip
    username: !secret unifi_user
    password: !secret unifi_pw
    consider_home: 180
    new_device_defaults:
      track_new_devices: False
      hide_if_away: False
# gpslogger:
person:

############ Remotes ############
remote:
  - platform: harmony
    name: Living Room
    host: !secret harmony_ip
    activity: 13474528


############ Media Players ############
media_player:
  - platform: samsungtv
    host: !secret samsungtv_ip
    name: Samsung TV
    mac: !secret samsungtv_mac
  - platform: braviatv
    host: !secret bravia_host
cast:


############ Google Assistant ############
google_assistant: !include google_assistant.yaml


############ Xiaomi Gateway ############
xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - host: !secret aqara_ip
      mac: !secret aqara_mac
      key: !secret aqara_key


############ Cameras ############
camera:
  ## xiaomi
  - platform: ffmpeg
    input: !secret cam1
    name: Study
  - platform: ffmpeg
    input: !secret cam2
    name: Family Room
  - platform: ffmpeg
    input: !secret cam3
    name: Kitchen
  ## swann/reolink
  # - platform: ffmpeg
  #   input: !secret reolink1
  #   name: Front 1
  # - platform: ffmpeg
  #   input: !secret reolink2
  #   name: Front 2
  # - platform: ffmpeg
  #   input: !secret reolink3
  #   name: Deck
  # - platform: ffmpeg
  #   input: !secret reolink4
  #   name: Side
  # - platform: ffmpeg
  #   input: !secret reolink5
  #   name: Backyard


############ Notifications ############
notify:
  - name: html5
    platform: html5
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key
    vapid_email: !secret vapid_email
  - name: gmail
    platform: smtp
    server: smtp.gmail.com
    port: 587
    timeout: 15
    sender: !secret smtp_email
    encryption: starttls
    username: !secret smtp_email
    password: !secret smtp_pw
    recipient:
      - !secret smtp_recipient1
    sender_name: My Home Assistant


############ IFTTT ############
ifttt:
  key: !secret ifttt_key


############ Shell ############
shell_command:
  server_shutdown: !secret server_shutdown


############ Weather ############
weather:
  - platform: bom
    station: !secret bom_station


############ Climate ############
smartir:
  update_branch: master

climate:
  - platform: smartir
    name: Bedroom
    unique_id: bedroom
    device_code: 1022
    controller_data: !secret broadlink_host1
    temperature_sensor: sensor.xiaomi_temp_1
    humidity_sensor: sensor.xiaomi_humidity_1
  - platform: harmony_ac
    name: Living Room
    remote_entity: remote.living_room
    device_id: 58354062
    min_temp: 18
    max_temp: 30
    target_temp: 20
    target_temp_step: 1
    temp_sensor: sensor.xiaomi_temp_2
    customize:
      operations:
        - cool
        - dry
        - heat
      fan_modes:
        - auto
        - low
        - med
        - high


############ Covers ############
cover:
  - platform: mqtt
    name: Garage Main
    state_topic: "cmnd/garage1_state/POWER2"
    command_topic: "cmnd/garage1/POWER"
    availability_topic: "tele/garage1/LWT"
    payload_open: "ON"
    payload_close: "ON"
    payload_stop: "ON"
    state_open: "OFF"
    state_closed: "ON"
    payload_available: "Online"
    payload_not_available: "Offline"
    optimistic: false

  - platform: mqtt
    name: Garage Rear
    state_topic: "cmnd/garage2_state/POWER2"
    command_topic: "cmnd/garage2/POWER"
    availability_topic: "tele/garage2/LWT"
    payload_open: "ON"
    payload_close: "ON"
    payload_stop: "ON"
    state_open: "OFF"
    state_closed: "ON"
    payload_available: "Online"
    payload_not_available: "Offline"
    optimistic: false

############ Zones ############
zone:
  - name: Work
    latitude: !secret lat1
    longitude: !secret long1
    icon: mdi:briefcase
  - name: Work
    latitude: !secret lat2
    longitude: !secret long2
    icon: mdi:briefcase
  - name: Gym
    latitude: !secret lat3
    longitude: !secret long3
    icon: mdi:dumbbell
    radius: 50
  - name: Gym
    latitude: !secret lat4
    longitude: !secret long4
    icon: mdi:dumbbell
    radius: 50


############ Binary Sensors ############
binary_sensor:
  - platform: ping
    name: Online
    host: 8.8.8.8
    count: 5
    scan_interval: 300


############ Vacuum ############
vacuum:
  - platform: xiaomi_miio
    host: !secret vacuum_ip
    token: !secret vacuum_token


############ Alarm ############
konnected:
  access_token: !secret konnected_token
  api_host: !secret hass_url
  devices:
    - id: !secret konnected_mac
      host: !secret konnected_host
      port: !secret konnected_port
      discovery: False
      binary_sensors:
        - zone: 1
          type: motion
        - zone: 2
          type: motion
        - zone: 3
          type: motion
        - zone: 4
          type: motion
        - zone: 5
          type: motion
        - zone: 6
          type: lock
      switches:
        - zone: out
          momentary: 500
          name: Alarm Toggle


speedtestdotnet:
  scan_interval:
    minutes: 23
  monitored_conditions:
    - ping
    - download
    - upload

############ Merged Files ############
sensor: !include_dir_merge_list sensors/
switch: !include_dir_merge_list switches/
light: !include_dir_merge_list lights/
script: !include_dir_merge_named scripts/
automation: !include automations.yaml
group: !include groups.yaml


# panel_iframe:
#   tasmota:
#     title: TasmoAdmin
#     icon: mdi:power-socket-au
#     url: 'https://192.168.1.19:9541/devices'
#   log:
#     title: Log Viewer
#     icon: mdi:book-open
#     url: 'https://192.168.1.19:4277'
