############################################################
# Title:    Home Assistant Configuration                   #
# Author:   so3n                                           #
# Navigation:                                              #
#   Basic Setup                                            #
#   History Filter                                         #
#   Inputs                                                 #
#   Device Trackers                                        #
#   Remotes                                                #
#   Media Players                                          #
#   Google Assistant                                       #
#   Xiaomi Gateway                                         #
#   Cameras                                                #
#   Notifications                                          #
#   IFTTT                                                  #
#   Shell                                                  #
#   Weather                                                #
#   Climate                                                #
#   Covers                                                 #
#   Zones                                                  #
#   Binary Sensors                                         #
#   Merged Files                                           #
#   No Longer Used                                         #
#                                                          #
############################################################


############ Basic Setup ############
homeassistant:
  name: !secret name
  latitude: !secret lat
  longitude: !secret long
  elevation: !secret elevation
  unit_system: metric
  time_zone: !secret timezone
  customize: !include customize.yaml
  whitelist_external_dirs:
    - /tmp
    - /share

http:
  # api_password: !secret http_pw
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  base_url: !secret url

frontend:
config:
updater:
hassio:
conversation:
# logger:
# introduction:
# discovery:
sun:
tts:
  platform: google


############ History Filter ############
history:
  exclude:
    domains:
      - automation
      - weblink
      - updater
      - script
    entities:
      - sensor.last_boot
      - sensor.since_last_boot
      - sensor.date


############ Logbook Filter ############
logbook:
  exclude:
    entities:
      - sensor.last_boot
      - sensor.since_last_boot
      - sensor.date
      - automation.home_server_on
      - automation.home_server_off
      - automation.samsung_tv_on
      - automation.samsung_tv_off
      - automation.ps4_on
      - automation.ps4_off
      - automation.harmony_input_selection
      - automation.harmony_off
      - automation.harmony_activity_sync
      - automation.fujitsu_selection_cool_20
      - automation.fujitsu_selection_off
    domains:
      - sun
      - weblink


############ Inputs ############
input_boolean:
  holiday_mode:
    name: Holiday Mode
    initial: off
    icon: mdi:airplane
  cast_visible:
    name: Cast Visible
    initial: on
    icon: mdi:cast


############ Device Trackers ############
device_tracker:
  - platform: gpslogger
  - platform: asuswrt
    host: !secret asus_ip
    username: !secret asus_user
    # password: !secret asus_pw
    ssh_key: !secret asus_key
    protocol: ssh
    port: 22
    consider_home: 300
    new_device_defaults:
      track_new_devices: False
      hide_if_away: False


############ Remotes ############
remote:
  - platform: harmony
    name: Living Room
    host: !secret harmony_ip
    activity: 13474528


############ Media Players ############
media_player:
  - platform: samsungtv
    host: !secret samsungtv_ip
    name: Samsung TV
    mac: !secret samsungtv_mac
  - platform: braviatv
    host: !secret bravia_host
  # - platform: ps4
    # host: !secret ps4_host
    # ps4_ip: !secret ps4_ip
    # name: PlayStation 4
    # local_store: games
cast:


############ Google Assistant ############
google_assistant:
  project_id: !secret ga_proj
  api_key: !secret ga_api
  expose_by_default: false
  entity_config:
    switch.arlec_1a:
      expose: true
      name: Fridge
    switch.arlec_1b:
      expose: true
      name: Outdoor Lights
    switch.arlec_1c:
      expose: true
      name: Fairy Lights
    switch.arlec_2a:
      expose: true
      name: Floor Lamp
    light.xiaomi_gateway_light:
      expose: true
    climate.bedroom:
      expose: true
      name: Bedroom Air Conditioner
    climate.living_room:
      expose: true
      name: Main Air Conditioner
    switch.template_home_server:
      expose: true
      name: Server
    switch.template_samsung_tv:
      expose: true
      name: Samsung TV
      aliases:
        - TV
    switch.template_soniq_tv:
      expose: true
      name: Bedroom TV
      aliases:
        - Soniq TV
        - TV
    switch.template_harmony_fetch:
      expose: true
      name: Fetch
    switch.template_harmony_tvsurround:
      expose: true
      name: Main TV
      aliases: 
        - TV
        - Sony TV

############ Xiaomi Gateway ############
xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - host: !secret aqara_ip
      mac: !secret aqara_mac
      key: !secret aqara_key


############ Cameras ############
camera:
  ## xiaomi
  - platform: ffmpeg
    input: !secret cam1
    name: Study
  - platform: ffmpeg
    input: !secret cam2
    name: Family Room
  - platform: ffmpeg
    input: !secret cam3
    name: Kitchen
  ## swann/reolink
  - platform: ffmpeg
    input: !secret reolink1
    name: Front 1
    extra_arguments: -pred 1 -q:v 2
  - platform: ffmpeg
    input: !secret reolink2
    name: Front 2
    extra_arguments: -q:v 32
  - platform: ffmpeg
    input: !secret reolink3
    name: Deck
  - platform: ffmpeg
    input: !secret reolink4
    name: Side
  - platform: ffmpeg
    input: !secret reolink5
    name: Backyard


############ Notifications ############
notify:
  - name: html5
    platform: html5
    gcm_api_key: !secret gcm-sender-key
    gcm_sender_id: !secret gcm-sender-id
  - name: gmail
    platform: smtp
    server: smtp.gmail.com
    port: 587
    timeout: 15
    sender: !secret smtp_email
    encryption: starttls
    username: !secret smtp_email
    password: !secret smtp_pw
    recipient:
      - !secret smtp_recipient1
    sender_name: My Home Assistant


############ IFTTT ############
ifttt:
  key: !secret ifttt_key


############ Shell ############
shell_command:
  server_shutdown: !secret server_shutdown


############ Weather ############
weather:
  - platform: bom
    station: !secret bom_station


############ Climate ############
climate:
  - platform: broadlink
    name: Bedroom
    host: !secret broadlink_host1
    mac: !secret broadlink_mac1
    ircodes_ini: 'www/climate_codes/panasonic.ini'
    min_temp: 16
    max_temp: 30
    target_temp: 20
    target_temp_step: 1
    temp_sensor: sensor.temp_bedroom
    default_operation: 'off'
    default_fan_mode: auto
    customize:
      operations:
        - 'off'
        - cool
        - dry
        - heat
      fan_modes:
        - low
        - mid
        - high
        - auto
  - platform: harmony
    name: Living Room
    host: !secret harmony_ip
    device_id: 58354062
    min_temp: 18
    max_temp: 30
    target_temp: 20
    target_temp_step: 1
    temp_sensor: sensor.temp_main
    default_operation: 'off'
    default_fan_mode: auto
    customize:
      operations:
        - 'off'
        - cool
        # - dry
        # - heat
      fan_modes:
        - low
        - med
        - high
        - auto


############ Covers ############
cover:
  - platform: mqtt
    name: "Garage"
    state_topic: "cmnd/garagestate/POWER2"
    command_topic: "cmnd/sonoffsv01/POWER"
    payload_open: "ON"
    payload_close: "ON"
    payload_stop: "ON"
    state_open: "OFF"
    state_closed: "ON"
    optimistic: false


############ Zones ############
zone:
  - name: Work
    latitude: !secret lat1
    longitude: !secret long1
    icon: mdi:briefcase
  - name: Work
    latitude: !secret lat2
    longitude: !secret long2
    icon: mdi:briefcase
  - name: Gym
    latitude: !secret lat3
    longitude: !secret long3
    icon: mdi:dumbbell
    radius: 50
  - name: Gym
    latitude: !secret lat4
    longitude: !secret long4
    icon: mdi:dumbbell
    radius: 50

############ Binary Sensors ############
binary_sensor:
  - platform: ping
    name: Online
    host: 8.8.8.8
    count: 5
    scan_interval: 300


############ Merged Files ############
sensor: !include_dir_merge_list sensors/
switch: !include_dir_merge_list switches/
script: !include_dir_merge_named scripts/
automation: !include_dir_merge_list automations/
group: !include groups.yaml
# device_tracker: !include_dir_merge_list device_trackers/
# shell_command: !include_dir_merge_named shell_command/
# remote: !include_dir_merge_list remotes/
# media_player: !include_dir_merge_list media_players/
# input_select: !include_dir_merge_named input_select/
# input_boolean: !include_dir_merge_named input_boolean/
# zone: !include_dir_merge_list zones/
# notify: !include_dir_merge_list notify/

