- platform: mqtt
  name: Garage Main
  state_topic: "stat/garage01/DOOR"
  command_topic: "cmnd/garage01/POWER"
  availability_topic: "tele/garage01/LWT"
  payload_open: "ON"
  payload_close: "ON"
  payload_stop: "ON"
  state_open: 0
  state_closed: 1
  payload_available: "Online"
  payload_not_available: "Offline"
  optimistic: false

- platform: mqtt
  name: Garage Rear
  state_topic: "stat/garage02/DOOR"
  command_topic: "cmnd/garage02/POWER"
  availability_topic: "tele/garage02/LWT"
  payload_open: "ON"
  payload_close: "ON"
  payload_stop: "ON"
  state_open: 0
  state_closed: 1
  payload_available: "Online"
  payload_not_available: "Offline"
  optimistic: false