- platform: asuswrt
  host: !secret asus_ip
  username: !secret asus_user
  password: !secret asus_pw
  protocol: ssh
  port: 22
  consider_home: 300
  new_device_defaults:
    track_new_devices: False
    hide_if_away: False