- alias: Fujitsu Selection (Cool 20)
  hide_entity: True
  trigger:
    - platform: state
      entity_id: input_select.aircon
      to: 'Cool Auto 20'
  action:
    - service: remote.send_command
      entity_id: remote.living_room
      data:
        device: 47350651
        command: Cool 20
    - service: input_select.select_option
      entity_id: input_select.aircon
      data_template:
        option: "Select..."
- alias: Fujitsu Selection (Off)
  hide_entity: True
  trigger:
    - platform: state
      entity_id: input_select.aircon
      to: 'Off'
  action:
    - service: remote.send_command
      entity_id: remote.living_room
      data:
        device: 47350651
        command: 'Off'
    - service: input_select.select_option
      entity_id: input_select.aircon
      data_template:
        option: "Select..."
                