### Show Home Server Health when powered on        
- alias: Home Server On
  hide_entity: True
  trigger:
    platform: state
    entity_id: sensor.hp_ilo_server_power
    to: 'ON'
  action:
    service: group.set_visibility
    entity_id: group.server1
    data:
      visible: True

### Hide Home Server Health when powered off      
- alias: Home Server Off
  hide_entity: True
  trigger:
    - platform: state
      entity_id: sensor.hp_ilo_server_power
      to: 'OFF'
    - platform: homeassistant
      event: start
  condition:
    # condition needed for homeassistant startup trigger
    condition: state
    entity_id: sensor.hp_ilo_server_power
    state: 'OFF'
  action:
    service: group.set_visibility
    entity_id: group.server1
    data:
      visible: False

### Show Samsung TV control when powered on
- alias: Samsung Tv On
  hide_entity: True
  trigger:
    platform: state
    entity_id: media_player.samsung_tv
    to: 'on'
  action:
    service: group.set_visibility
    entity_id: group.samsung_tv
    data:
      visible: True
 
 ### Hide Samsung TV control when powered off
- alias: Samsung Tv Off
  hide_entity: True
  trigger:
    - platform: state
      entity_id: media_player.samsung_tv
      to: 'off'
    - platform: homeassistant
      event: start
  condition:
    # condition needed for homeassistant startup trigger
    condition: state
    entity_id: media_player.samsung_tv
    state: 'off'
  action:
    service: group.set_visibility
    entity_id: group.samsung_tv
    data:
      visible: False