#### Action for Harmony input selection
- alias: Harmony Input Selection
  hide_entity: True
  trigger:
    - platform: state
      entity_id: input_select.harmony
      to: 'Watch TV'
    - platform: state
      entity_id: input_select.harmony
      to: 'Watch TV with Surround'
    - platform: state
      entity_id: input_select.harmony
      to: 'Watch Fetch'
    - platform: state
      entity_id: input_select.harmony
      to: 'Watch Netflix'
    - platform: state
      entity_id: input_select.harmony
      to: 'Play PS4'
  action:
    - service: remote.turn_on
      entity_id: remote.living_room
      data_template:
        activity: >
          {% if is_state("input_select.harmony", "Watch TV") %}
            21450129
          {% elif is_state("input_select.harmony", "Watch TV with Surround") %}
            13915533
          {% elif is_state("input_select.harmony", "Watch Fetch") %}
            13474528
          {% elif is_state("input_select.harmony", "Watch Netflix") %}
            28400181
          {% elif is_state("input_select.harmony", "Play PS4") %}
            13332151
          {% else %}
          {% endif %}

#### Action for Harmony input selection to Power-Off
- alias: Harmony Off
  hide_entity: True
  trigger:
    platform: state
    entity_id: input_select.harmony
    to: 'Power Off'
  action:
    - service: remote.turn_off
      entity_id: remote.living_room

#### Keep Harmony input selection in sync with Harmony Hub        
- alias: Harmony Activity Sync
  hide_entity: True
  trigger:
    - platform: template
      value_template: "{% if is_state_attr('remote.living_room', 'current_activity', 'Watch TV') %}true{% endif %}"
    - platform: template
      value_template: "{% if is_state_attr('remote.living_room', 'current_activity', 'TV and surround') %}true{% endif %}"
    - platform: template
      value_template: "{% if is_state_attr('remote.living_room', 'current_activity', 'Watch Fetch') %}true{% endif %}"
    - platform: template
      value_template: "{% if is_state_attr('remote.living_room', 'current_activity', 'Watch Netflix') %}true{% endif %}"
    - platform: template
      value_template: "{% if is_state_attr('remote.living_room', 'current_activity', 'Play PS4') %}true{% endif %}"
    - platform: template
      value_template: "{% if is_state_attr('remote.living_room', 'current_activity', 'PowerOff') %}true{% endif %}"
  action:
    - service: input_select.select_option
      entity_id: input_select.harmony
      data_template:
        option: >
          {% if is_state_attr('remote.living_room', 'current_activity', 'Watch TV') %}
            Watch TV
          {% elif is_state_attr('remote.living_room', 'current_activity', 'TV and surround') %}
            Watch TV with Surround
          {% elif is_state_attr('remote.living_room', 'current_activity', 'Watch Fetch') %}
            Watch Fetch
          {% elif is_state_attr('remote.living_room', 'current_activity', 'Watch Netflix') %}
            Watch Netflix
          {% elif is_state_attr('remote.living_room', 'current_activity', 'Play PS4') %}
            Play PS4
          {% elif is_state_attr('remote.living_room', 'current_activity', 'PowerOff') %}
            Power Off
          {% else %}
          {% endif %}

